#!/bin/bash
# Written by Dan Klassen <dan@triplei.ca>
# Last Updated - 2016-05-13

VERSION="1.0.0"
VSCALE="480:-1"

help() {
    echo "Video 4 Everybody Conversion script v$VERSION"
    echo ""
    echo "Convert the passed in video file to various formats for the web"
    echo "OPTIONS:"
    echo "-i input file (required)"
    echo "-o output file (required)"
    echo "-v video scaling (defaults to 480:-1 to preserver aspect ratio)"
    exit 0
}

if [ $# == 0 ]; then
    help
fi

while getopts "hi:o:v:" opt; do
    case $opt in
        h)
            help
            exit 0
            ;;
        i)
            FILENAME="$OPTARG" >&2
            ;;
        o)
            OUTPUT="$OPTARG" >&2
            ;;
        v)
            VSCALE=$OPTARG >&2
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument" >&2
            exit 1
            ;;
    esac
done

if [ ! -e "$FILENAME" ]; then
    echo "$FILENAME does not exist" >&2
    exit 1
fi

if [ -z $OUTPUT ]; then
    echo "please set -o with the base output file name (no extension)" >&2
    exit 1
fi

echo "Processing $FILENAME"

echo "Creating .mp4 version"
ffmpeg -i "$FILENAME" -codec:v libx264 -preset slow -profile:v main -crf 20 -codec:a aac -ab 128k -vf scale="$VSCALE" "$OUTPUT".mp4
echo "Creating .ogv version"
ffmpeg -i "$FILENAME" -codec:v libtheora -q:v 6 -codec:a libvorbis -ab 128k -vf scale="$VSCALE" "$OUTPUT".ogv
echo "Creating .webm version"
ffmpeg -i "$FILENAME" -codec:v libvpx -q:v 6 -codec:a libvorbis -ab 128k -vf scale="$VSCALE" "$OUTPUT".webm
echo "done"
exit 0